config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "courses#index"
  resources :courses
  get 'account/new', to: "accounts#new"
  post 'accounts', to: "accounts#create"

  get 'accounts/login', to: "sessions#new"
  post 'accounts/sessions', to: "sessions#create"
  delete 'accounts/logout', to: "sessions#destroy"

  post "courses/:id/enroll", to: "courses#enroll"

  namespace :admin do
    root to: "courses#index"
    resources :accounts
  end
end

app/models/account.rb
require 'bcrypt'
class Account < ApplicationRecord
  attr_accessor :password

  before_save :encrypt_password

  has_many :course_students, foreign_key: :student_id
  has_many :courses, through: :course_students

  enum role: [:admin, :student]

  def encrypt_password
    if self.password.present?
      self.encrypted_password = BCrypt::Password.create(self.password)
    end
  end



 def self.authenticate(email, password)
  acc = Account.where(email: email).first

  return false unless acc && acc.encrypted_password

  if BCrypt::Password.new(acc.encrypted_password) == password
    return acc
  else
     return false
   end
 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :course_students
    has_many :students, class_name: "Account", through: :course_students
end


#a.errors.full_messages

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :course
  belongs_to :student, class_name: "Account", foreign_key: :student_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate_account!, only: [:new, :create]
  def new
    @account = Account.new
  end

  def create
    #binding.pry

    @account = Account.new(account_params)
    if @account.save
      @current_account = Account.where(id: session[:current_account_id]).first
      if @current_account.role == "admin"
        redirect_to admin_accounts_path
      else
        redirect_to root_path
      end
    else
      render :new
    end
  end

  private
  def account_params
    params.require(:account).permit(:name, :email, :password)
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < AdminController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find_by id: params[:id]
  end

  def destroy
    @account = Account.find_by id: params[:id]
    @account.destroy
    redirect_to admin_accounts_path
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def authenticate_admin!
    redirect_to root_path if @current_account.role != "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_account!
  skip_before_action :authenticate_account!, only: [:new, :create]
  def authenticate_account!
    if session[:current_account_id]
      @current_account = Account.where(id: session[:current_account_id]).first
    end

    return redirect_to accounts_login_path unless @current_account
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
    respond_to do |format|
      format.html
      format.json {render json: {courses: @courses}}
    end
	end

  def enroll
    @course_student = CourseStudent.create(student_id: @current_account.id, course_id: params[:id])

    respond_to do |format|
      #format.html
      format.js
      format.json {render json: {status: :ok}}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authenticate_account!, only: [:new, :create]

  def new
      redirect_to root_path if session[:current_account_id]
  end

  def create
    authorized_account = Account.authenticate(params[:email], params[:password])
    if authorized_account
      session[:current_account_id] = authorized_account.id
      redirect_to authorized_account.role == "admin" ? admin_root_path : root_path
    else
      render :new
    end
  end

  def destroy
    session[:current_account_id] = nil
    redirect_to accounts_login_path
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/new.html.erb
<!--m class>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="pwd">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
-->
<%=  form_for @account, url: {action: "create"}, html: {class: "col-md-6 col-md-offset-3"}  do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>

    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control'%>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control'%>

    <br />
    <%= f.submit "Create" %>
<% end %>

app/views/admin/accounts/index.html.erb
<div id="right">
  <h1 style="text-align: center">User</h1>
  <ul class="users">
  <h4><%= link_to "New_user", account_new_path  %></h4>
    <% @accounts.each do |account| %>
      <li>
        <%= link_to account.name, admin_account_path(account) %>
            <%= link_to "Delete", admin_account_path(account), method: :delete,
          data: {confirm: "You sure?"} %>
      </li>
    <% end %>
  </ul>
</div>

app/views/admin/accounts/show.html.erb
<div id="right">
  <h4><%= @account.name %></h4>
  <h4><%= @account.email %></h4>
</div>

app/views/courses/enroll.js.erb
$("#course-<%= @course_student.course_id %>").fadeOut(500);

app/views/courses/index.html.erb
 <div id="course-index">
    <div class="container">
		<div class="row">

			<% @courses.each do |course| %>

				<div class="col-sm-4" id="course-<%= course.id %>">
					<div id="card" class="weater">
						<div class="city-selected">
							<article>
								<div class="info">
									<div class="city"><%= course.name %></div>
									<div class="night">Night - 22:07 PM</div>

									<div class="temp">3°</div>
								</div>

								<div class="icon">

								</div>

							</article>

							<figure style="background-image: url(http://136.243.1.253/~creolitic/bootsnipp/home.jpg)"></figure>
						</div>

						<div class="days">
							<div class="btn btn-success btn-enrollment" data-id="<%= course.id %>">
							Enroll
							</div>
						</div>
					</div>
				</div>

			<% end %>

		</div>
	</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lms</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
  table, td {
      border: 1px solid black;
      border-collapse: collapse;
      width: 70%;
      margin-left: 40px;
      font-size: 20px;
  }
  </style>
</head>

<body>
  <%= render 'shared/header' %>
  <div id="left">
    <h1>Admin</h1>
    <table style="width:80%" >
      <tr>
        <td><%= link_to "Courses", "#" %></td>
      </tr>
      <tr>
        <td><%= link_to "Users", admin_accounts_path %></td>
      </tr>
      <tr>
        <td><%= link_to "Lession", "#" %></td>
      </tr>
    </table>
  </div>
    <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/header' %>
    <%= yield %>




  </body>

</html>

app/views/shared/_footer.html.erb
    <footer>
      <div class="footer">
        <div class="container">
                <a href='#'><i class="fa fa-twitch fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-facebook fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-twitter fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-youtube-play fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-rss fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-vine fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-flickr fa-3x fa-fw"></i></a>
                <a href='#'><i class="fa fa-linkedin fa-3x fa-fw"></i></a>
              </span>
        </div>
      </div>
    </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">WebSiteName</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
        <%= link_to 'Home', root_path %>
        </li>

        <li>
          <% if session[:current_account_id] %>
            <%= link_to accounts_logout_path, method: :delete do %>
              Logout
              <% end %>
          <% else %>
            <%= link_to 'Login', accounts_login_path %>
          <% end %>
        </li>


      </ul>
  </div>
</nav>